openapi: 3.0.0
info:
  title: Driving API Documentation
  version: 1.0.0
  description: API for managing student records and company services

tags:
  - name: Students
    description: Operations related to student records
  - name: Company Services
    description: Operations related to services offered by the company

paths:

  /api/v1/students/add_student:
    post:
      summary: Add a new student
      description: Create a new student record in the system
      tags:
        - Students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - gender
                - email
                - serviceType
              properties:
                firstName:
                  type: string
                  example: John
                lastName:
                  type: string
                  example: Doe
                otherName:
                  type: string
                  example: Michael
                gender:
                  type: string
                  enum: [Male, Female]
                  example: Male
                email:
                  type: string
                  format: email
                  example: john.doe@example.com
                phoneOne:
                  type: string
                  example: "08012345678"
                phoneTwo:
                  type: string
                  example: "08098765432"
                serviceType:
                  type: string
                  example: Driving Lesson
      responses:
        '201':
          description: Student created successfully
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Validation failed
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Internal server error

  /api/v1/students/fetch_students:
    get:
      summary: Fetch all students
      description: Retrieve a list of all registered students
      tags:
        - Students
      responses:
        '200':
          description: A list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    studentId:
                      type: string
                      example: STU2024-001
                    firstName:
                      type: string
                      example: John
                    lastName:
                      type: string
                      example: Doe
                    otherName:
                      type: string
                      example: Michael
                    gender:
                      type: string
                      example: Male
                    email:
                      type: string
                      example: john.doe@example.com
                    phoneOne:
                      type: string
                      example: "08012345678"
                    phoneTwo:
                      type: string
                      example: "08098765432"
                    serviceType:
                      type: string
                      example: Driving Lesson
                    createdAt:
                      type: string
                      format: date-time
                      example: 2024-05-20T10:00:00Z
                    updatedAt:
                      type: string
                      format: date-time
                      example: 2024-05-21T14:30:00Z
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Internal server error

  /api/v1/students/search_student:
    get:
      summary: Search for students
      description: Search students by name, email, or service type
      tags:
        - Students
      parameters:
        - in: query
          name: firstName
          schema:
            type: string
          description: Filter by first name
        - in: query
          name: lastName
          schema:
            type: string
          description: Filter by last name
        - in: query
          name: email
          schema:
            type: string
            format: email
          description: Filter by email
        - in: query
          name: serviceType
          schema:
            type: string
          description: Filter by service type
      responses:
        '200':
          description: Matching students found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    studentId:
                      type: string
                      example: STU2024-001
                    firstName:
                      type: string
                      example: John
                    lastName:
                      type: string
                      example: Doe
                    email:
                      type: string
                      example: john.doe@example.com
                    serviceType:
                      type: string
                      example: Driving Lesson
        '400':
          description: Invalid search criteria
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid search query
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Internal server error

  /api/v1/services/add_newService:
    post:
      summary: Add a new Company Service
      description: Add a service offered by the organization
      tags:
        - Company Services
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - serviceType
                - serviceDescription
                - fee
                - duration
              properties:
                serviceType:
                  type: string
                  example: Driving Test Preparation
                serviceDescription:
                  type: string
                  example: An intensive course to prepare students for the road test.
                fee:
                  type: string
                  example: "15000"
                duration:
                  type: string
                  example: 4 weeks
      responses:
        '201':
          description: Service created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Service added successfully
                  data:
                    type: object
                    properties:
                      serviceId:
                        type: string
                        example: SVC-54893
                      serviceType:
                        type: string
                        example: Driving Test Preparation
                      serviceDescription:
                        type: string
                        example: An intensive course to prepare students for the road test.
                      fee:
                        type: string
                        example: "15000"
                      duration:
                        type: string
                        example: 4 weeks
                      createdAt:
                        type: string
                        format: date-time
                        example: 2025-06-03T10:20:00Z
                      updatedAt:
                        type: string
                        format: date-time
                        example: 2025-06-03T10:20:00Z
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Validation error
        '409':
          description: Service already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Service already exists
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Internal server error

  /api/v1/services/getAllServices:
    get:
      summary: Get Registered Services
      description: Retrieve a list of all registered services
      tags:
        - Company Services
      responses:
        '200':
          description: A list of services
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Web Development
                    description:
                      type: string
                      example: Building websites and web applications
                    createdAt:
                      type: string
                      format: date-time
                      example: "2025-06-04T12:34:56Z"
                    updatedAt:
                      type: string
                      format: date-time
                      example: "2025-06-04T12:34:56Z"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Internal server error

  /api/v1/services/delete_service/{serviceId}:
    delete:
      summary: Delete a registered service
      description: Deletes a specific service by its serviceId
      tags:
        - Company Services
    parameters:
      - in: path
        name: serviceId
        required: true
        schema:
          type: string
        description: ID of the service to delete
    responses:
      '200':
        description: Service deleted successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                msg:
                  type: string
                  example: Service deleted successfully
      '400':
        description: Service ID is missing or invalid
        content:
          application/json:
            schema:
              type: object
              properties:
                msg:
                  type: string
                  example: Service ID is required to delete
      '404':
        description: Service not found
        content:
          application/json:
            schema:
              type: object
              properties:
                msg:
                  type: string
                  example: Service not found
      '500':
        description: Internal server error
        content:
          application/json:
            schema:
              type: object
              properties:
                msg:
                  type: string
                  example: Internal server error

